### ISSUE TITLE
Email password escaped ?

### ISSUE THREAD

**Issue by Ti133700N** [ninthwalker/NowShowing#34]
I'm having issue when sending emails. It's telling me the authentication failed, and I can notice the same thing on my mail server logs, clearly it's trying to log in with the wrong info. I'm pretty confident in the settings I'm using since I use the exact same on the same machine from Thunderbird and it's working fine. Since I may or may not have double quotes in my password (and also the username contains an '@' char), I'm wondering if those 2 infos are properly handled / escaped ? Thanks.

**Comment by ninthwalker** [comment]
It should do special password characters fine. 
You said 'your mail server'. Do you mean you run your own? If so, this may or may not work for you. 
First it needs to go through an ssl/tls port. 
Second, since gmail is most popular we use the AUTH type of 'plain'. Your mail server may use a different type such as Login or something.

So you may have to use a different mail provider for this.

**Comment by Ti133700N** [comment]
Thanks for the quick reply. I use my own mail server indeed (that I configured from scratch). I'm using STARTTLS on port 588 and Plain Auth.

**Comment by Ti133700N** [comment]
Now I'm getting this error when doing `docker exec nowshowing combinedreport `
`/var/lib/nowshowing/mailReport.rb:60:in `sendMail': undefined method `each' for nil:NilClass (NoMethodError)
	from /usr/local/sbin/combinedreport:386:in `main'
	from /usr/local/sbin/combinedreport:394:in `<main>'
`

**Comment by ninthwalker** [comment]
It's still not working and giving errors because of your mail server setup most likely. The code used just may not be compatible with your server.

Here is the block of code for sending the email. Like mentioned earlier, this was set for gmail primarily. You could try editing this file manually in the docker with vi and fooling around with it. It's located at "/var/lib/nowshowing/mailReport.rb"

`def sendMail(body)
        options = { :address              => $config['mail']['address'],
                    :port                 => $port,
                    :domain               => 'otherdomain.com',
                    :user_name            => $config['mail']['username'],
                    :password             => $config['mail']['password'],
                    :authentication       => 'plain',
                    :enable_starttls_auto => true  }
            Mail.defaults do
            delivery_method :smtp, options
end
`

**Comment by ninthwalker** [comment]
Closing
